const ADD_TODO = 'ADD_TODO';
const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
const TOGGLE_TODO = 'TOGGLE_TODO';
const SHOW_ALL = 'SHOW_ALL';
const SHOW_COMPLETED = 'SHOW_COMPLETED';
const SHOW_ACTIVE = 'SHOW_ACTIVE';

export {
  ADD_TODO,
  SET_VISIBILITY_FILTER,
  TOGGLE_TODO,
  SHOW_ALL,
  SHOW_COMPLETED,
  SHOW_ACTIVE,
};
